Traceback (most recent call last):
  File "test_line.py", line 54, in <module>
    test(opt)
  File "test_line.py", line 29, in test
    Detector = detector_factory[opt.dataset]
KeyError: 'roboline'
